stages:
  - name: build
    steps:
      - runScriptConfig:
          image: maven:3.6.0-jdk-8-alpine
          shellScript: mvn clean package
  - name: push-image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: taotao-cloud/ui:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: http://192.168.214.131:88/
  - name: deploy
    steps:
      - applyYamlConfig:
          path: ./Deployment.yaml
timeout: 60
