stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3.6.0-jdk-8-alpine
          shellScript: mvn clean package
  - name: PushImage
    steps:
      - publishImageConfig:
          dockerfilePath: ./taotao-cloud-auth/Dockerfile
          buildContext: ./taotao-cloud-auth
          tag: taotao-cloud/taotao-cloud-auth:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: http://172.16.10.220:88/taotao-cloud
#  - name: Deploy
#    steps:
#      - applyYamlConfig:
#          path: ./Deployment.yaml
timeout: 60
